name: kinopark
description: "A project for Kinopark VIP cinema"

publish_to: 'none'

version: 1.0.0+13

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  cupertino_icons: ^1.0.8
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  dio: ^5.7.0
  shared_preferences: ^2.3.3
  hive: ^2.2.3
  freezed: ^2.5.7
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  path_provider: ^2.1.5
  hive_generator: ^2.0.1
  hive_flutter: ^1.1.0
  web_socket_channel: ^3.0.1
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  uuid: ^4.5.1
  package_info_plus: ^8.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/
    - assets/flags/
